require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe FountainsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Fountain. As you add validations to Fountain, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FountainsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all fountains as @fountains" do
      fountain = Fountain.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:fountains)).to eq([fountain])
    end
  end

  describe "GET show" do
    it "assigns the requested fountain as @fountain" do
      fountain = Fountain.create! valid_attributes
      get :show, {:id => fountain.to_param}, valid_session
      expect(assigns(:fountain)).to eq(fountain)
    end
  end

  describe "GET new" do
    it "assigns a new fountain as @fountain" do
      get :new, {}, valid_session
      expect(assigns(:fountain)).to be_a_new(Fountain)
    end
  end

  describe "GET edit" do
    it "assigns the requested fountain as @fountain" do
      fountain = Fountain.create! valid_attributes
      get :edit, {:id => fountain.to_param}, valid_session
      expect(assigns(:fountain)).to eq(fountain)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Fountain" do
        expect {
          post :create, {:fountain => valid_attributes}, valid_session
        }.to change(Fountain, :count).by(1)
      end

      it "assigns a newly created fountain as @fountain" do
        post :create, {:fountain => valid_attributes}, valid_session
        expect(assigns(:fountain)).to be_a(Fountain)
        expect(assigns(:fountain)).to be_persisted
      end

      it "redirects to the created fountain" do
        post :create, {:fountain => valid_attributes}, valid_session
        expect(response).to redirect_to(Fountain.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved fountain as @fountain" do
        post :create, {:fountain => invalid_attributes}, valid_session
        expect(assigns(:fountain)).to be_a_new(Fountain)
      end

      it "re-renders the 'new' template" do
        post :create, {:fountain => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested fountain" do
        fountain = Fountain.create! valid_attributes
        put :update, {:id => fountain.to_param, :fountain => new_attributes}, valid_session
        fountain.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested fountain as @fountain" do
        fountain = Fountain.create! valid_attributes
        put :update, {:id => fountain.to_param, :fountain => valid_attributes}, valid_session
        expect(assigns(:fountain)).to eq(fountain)
      end

      it "redirects to the fountain" do
        fountain = Fountain.create! valid_attributes
        put :update, {:id => fountain.to_param, :fountain => valid_attributes}, valid_session
        expect(response).to redirect_to(fountain)
      end
    end

    describe "with invalid params" do
      it "assigns the fountain as @fountain" do
        fountain = Fountain.create! valid_attributes
        put :update, {:id => fountain.to_param, :fountain => invalid_attributes}, valid_session
        expect(assigns(:fountain)).to eq(fountain)
      end

      it "re-renders the 'edit' template" do
        fountain = Fountain.create! valid_attributes
        put :update, {:id => fountain.to_param, :fountain => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested fountain" do
      fountain = Fountain.create! valid_attributes
      expect {
        delete :destroy, {:id => fountain.to_param}, valid_session
      }.to change(Fountain, :count).by(-1)
    end

    it "redirects to the fountains list" do
      fountain = Fountain.create! valid_attributes
      delete :destroy, {:id => fountain.to_param}, valid_session
      expect(response).to redirect_to(fountains_url)
    end
  end

end
